# config.yaml
openai:
  api_key: "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"
